license = "All rights reserved"
loaderVersion = "[36,)"
modLoader = "javafml"
[[mods]]
displayName = "Steelworks"
modId = "steelworks"
version = "${file.jarVersion}"
# logoFile="examplemod.png"
authors = "Raven, shiroroku"
credits = ""
description = '''
descriptionnnnnnnnnnnnnnnnnnn
'''
[[dependencies.steelworks]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[36,)"
[[dependencies.steelworks]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.16.5,1.17)"
[[dependencies.steelworks]]
mandatory=true
modId="geckolib3"
ordering="BEFORE"
side="BOTH"
versionRange="[3.0.65,)"